# Classic seq-SD with lossy verification
method: classic_seq_sd

llm_path: meta-llama/Llama-3.1-70B-Instruct
draft_model_path: meta-llama/Llama-3.1-8B-Instruct

recipe: null
device: auto

max_length: 2048
cache_implementation:
  target: dynamic
  draft: static
warmup_iter: 1
compile_mode: 
  target: null
  draft: max-autotune

# Target sampling settings (defaults)
# Suggested setting
# 1. Llama Model
#    - do_sample: true / false
#    - temperature: 0.6 / null
#    - top_p: 0.9 / null
# 2. Qwen3 Model with enable_thinking=true
#    - do_sample: true
#    - temperature: 0.6
#    - top_p: 0.95
#    - top_k: 20
#    - min_p: 0.0
# 3. Qwen3 Model with enable_thinking=false
#    - do_sample: true
#    - temperature: 0.7
#    - top_p: 0.8
#    - top_k: 20
#    - min_p: 0.0

do_sample: false
# temperature: 0.6
# top_k: 20
# top_p: 0.9
# min_p: 0.0

generator_profiling: true

generator_kwargs:
  enable_thinking: false
  prefill_chunk_size: 256
  verify_method: edit
  verify_kwargs:
    threshold: 0.04
    window_size: 12
    max_edit: 2
    # min_interval: 3

draft_params:
  # do_sample: true
  draft_threshold: 0.15
  max_depth: 16
  topk_len: 1
