# Classic seq-SD with exact verification
method: classic_seq_sd

llm_path: meta-llama/Llama-3.1-70B-Instruct
draft_model_path: meta-llama/Llama-3.1-8B-Instruct

recipe: null
device: auto

max_length: 2048
cache_implementation:
  target: dynamic
  draft: static
warmup_iter: 1
compile_mode: 
  target: null
  draft: max-autotune

# Target sampling settings (defaults)
do_sample: false
# temperature: 0.6
# top_p: 0.9

generator_profiling: true

generator_kwargs:
  prefill_chunk_size: 2048
  verify_method: exact
  verify_kwargs: {}

draft_params:
  temperature: 1.0
  max_depth: 10
  topk_len: 1
